# For full config options, check the docs:
#    docs.serverless.com
service: serverless-template

plugins:
  - serverless-plugin-typescript
  - serverless-stack-output
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: eu-south-2

custom:
  stage: ${opt:stage, 'dev'}
  output:
    file: .serverless/output.json

functions:
  healthcheck:
    handler: src/functions/healthcheck.healthcheck
    description: Healthcheck to ensure the service is up
    events:
      - http:
          path: healthcheck
          method: get
