service: ai-service

provider:
  name: aws
  runtime: python3.8

functions:
  api:
    handler: handler.chat_completions
    events:
      - http:
          path: chat/completions
          method: post
plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  serverless-offline:
    httpPort: 5000